name: Weekly EUTTC Signup

on:
  schedule:
    # 每周二 9:30 AM UK时间
    - cron: '30 9 * 10-12,1-3 2'   # 冬令时: 9:30 UTC = 9:30 AM GMT
    - cron: '30 8 * 4-9 2'         # 夏令时: 8:30 UTC = 9:30 AM BST
    
    # 每周二 4:00 PM UK时间
    - cron: '0 16 * 10-12,1-3 2'   # 冬令时: 16:00 UTC = 4:00 PM GMT
    - cron: '0 15 * 4-9 2'         # 夏令时: 15:00 UTC = 4:00 PM BST
  workflow_dispatch:

jobs:
  signup:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: 安装Google Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        CHROME_VERSION=$(google-chrome --version)
        echo "✅ 安装的Chrome版本: $CHROME_VERSION"
    
    - name: 安装匹配的ChromeDriver
      run: |
        # 获取Chrome主版本号
        CHROME_FULL_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        CHROME_MAJOR_VERSION=$(echo $CHROME_FULL_VERSION | cut -d. -f1)
        echo "Chrome完整版本: $CHROME_FULL_VERSION"
        echo "Chrome主版本: $CHROME_MAJOR_VERSION"
        
        # 获取对应的ChromeDriver版本
        CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROME_MAJOR_VERSION")
        echo "匹配的ChromeDriver版本: $CHROMEDRIVER_VERSION"
        
        # 下载ChromeDriver
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
        unzip -q chromedriver-linux64.zip
        
        # 替换系统ChromeDriver
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
        
        # 验证
        DRIVER_VERSION=$(chromedriver --version)
        echo "✅ ChromeDriver版本: $DRIVER_VERSION"
    
    - name: 安装Python依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 显示环境信息
      run: |
        echo "======================================"
        echo "🐍 Python: $(python --version)"
        echo "🌐 Chrome: $(google-chrome --version)"
        echo "🚗 ChromeDriver: $(chromedriver --version)"
        echo "🕐 系统时间: $(date)"
        echo "🇬🇧 UK时间: $(TZ='Europe/London' date)"
        echo "======================================"
    
    - name: 运行预约脚本
      env:
        FIRST_NAME: ${{ secrets.FIRST_NAME }}
        LAST_NAME: ${{ secrets.LAST_NAME }}
        EMAIL: ${{ secrets.EMAIL }}
      run: |
        echo "🏓 开始执行EUTTC预约脚本..."
        python TableTennisSignUpBot.py
        EXIT_CODE=$?
        echo "脚本执行完成，退出码: $EXIT_CODE"
        exit $EXIT_CODE
    
    - name: 上传日志和截图
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: signup-logs-${{ github.run_number }}
        path: |
          *.log
          *.png
        retention-days: 30
        if-no-files-found: warn
    
    - name: 输出执行结果
      if: always()
      run: |
        echo "=========================================="
        echo "📊 执行状态: ${{ job.status }}"
        echo "=========================================="
        if [ -f signup_bot.log ]; then
          echo ""
          echo "📋 日志内容（最后30行）:"
          echo "=========================================="
          tail -n 30 signup_bot.log
        else
          echo "⚠️ 未找到日志文件"
        fi
        echo "=========================================="
